GET http://localhost:9999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjE3OTcyMTUsImV4cCI6MTYyMTc5NzI0NSwiYXVkIjoiNjBhYThlNWY2MTY0NzYyNTc0YjQwZjk2IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.FI8IRDFIyGhds7nYGqz3zPnf_Jr8I2nyM9SJbBIjWhw


###
GET http://localhost:9999/abc_asd

### Login Route
POST http://localhost:9999/auth/login
Content-Type: application/json

{
    "email" : "nikitamirzani323458@gmail.com",
    "password" : "abcd1234"
}

### Register Route
POST http://localhost:9999/auth/register
Content-Type: application/json

{
    "email" : "edo@gmail.com",
    "password" : "abcd1234"
}

### Refresh Token Route
POST http://localhost:9999/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjE3OTcyOTUsImV4cCI6MTYyMTc5NzMyNSwiYXVkIjoiNjBhYThlNWY2MTY0NzYyNTc0YjQwZjk2IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.cz2z5ujgRqty4lMmOdUnbFylFqbnFeSU1N3XxuXsEVI"
}

### Logout Route
DELETE http://localhost:9999/auth/logout